#pragma kernel CSScaleDepthBuffer

#define THREADS 16
#define GROUPS 16

#define MAX_RANGE_16BITS 65535.0
#define MAX_RANGE_8BITS 255.0

StructuredBuffer<float> _Input;
RWStructuredBuffer<uint> _Output;

float _DepthMin;
float _DepthMax;
float _DepthScale;
uint _Width;
int _UnitSize;

[numthreads(THREADS, GROUPS, 1)]
void CSScaleDepthBuffer(uint3 id : SV_DispatchThreadID)
{
	const uint bufIndex = id.y *_Width + id.x;
	if (bufIndex >= _Width * GROUPS)
		return;
	// const float data = _Input.Load(bufIndex);
	// const float data = _Input[bufIndex];
	// const float rangedData = data * _DepthMax;

	float z = _Input[bufIndex];
    float linearDepth = (_DepthMax * _DepthMin) / (_DepthMax - z * (_DepthMax - _DepthMin));

  	float rangedData = linearDepth * _DepthScale;
	uint finalData = 0;

	if (_UnitSize == 4)
	{
		finalData = asuint(rangedData);
	}
	else if (_UnitSize == 2)
	{
		const float max_scaled_range = MAX_RANGE_16BITS / _DepthScale;
        const float scaledData = ((rangedData > max_scaled_range) ? max_scaled_range : rangedData) * _DepthScale;
        finalData = (uint)scaledData & 0xFFFF;
	}
	else // 1
	{
		const float scaledData = rangedData / _DepthMax * MAX_RANGE_8BITS;
        finalData = (uint)scaledData & 0xFF;
	}
	_Output[bufIndex] = finalData;
}